# # Use phusion/passenger-full as base image. To make your builds reproducible, make
# # sure you lock down to a specific version, not to `latest`!
# # See https://github.com/phusion/passenger-docker/blob/master/Changelog.md for
# # a list of version numbers.
mysql:
    image: mysql:5.7.10
    environment:
        MYSQL_DATABASE: cs4501
        MYSQL_USER: root
        DATABASE_PASSWORD: S3cure
        MYSQL_ROOT_PASSWORD: S3cure
web:
    build: .
    ports:
        - "8000:8000"
    command: bash -c "python /app/marketplace/manage.py migrate && mod_wsgi-express start-server --working-directory /app/marketplace /app/marketplace/marketplace_of_ideas/wsgi.py" &
    links:
        - mysql
# EXAMPLE TEMPLATE: 
# models:
#    image: tp33/django:1.2
#    external_links:
#       - mysql:db
#    ports:
#       - "8001:8000"
#    volumes:
#       - /home/tp/stuff-models:/app
#    command: "mod_wsgi-express start-server --reload-on-changes stuff-models/wsgi.py"

# exp:
#    image: tp33/django:1.2
#    links:
#       - models:models-api
#    ports:
#       - "8002:8000"
#    volumes:
#       - /home/tp/stuff-exp:/app
#    command: "mod_wsgi-express start-server --reload-on-changes stuff-exp/wsgi.py"

# web:
#    image: tp33/django:1.2
#    links:
#       - exp:exp-api
#    ports:
#       - "8000:8000"
#    volumes:
#       - /home/tp/stuff-web:/app
#    command: "mod_wsgi-express start-server --reload-on-changes stuff-web/wsgi.py"