# # Use phusion/passenger-full as base image. To make your builds reproducible, make
# # sure you lock down to a specific version, not to `latest`!
# # See https://github.com/phusion/passenger-docker/blob/master/Changelog.md for
# # a list of version numbers.
kafka: 
    image: spotify/kafka
    container_name: kafka
    environment:
        ADVERTISED_HOST: kafka
        ADVERTISED_PORT: 9092
    hostname: kafka
es:
    image: elasticsearch:2.0
    container_name: es
    ports:
        - "9200:9200"
batch:
    image: tp33/django-docker:1.3
    container_name: batch
    links:
        - kafka:kafka
        - es:es
    volumes:
        - ./indexer:/app
    command: bash -c "python /app/indexer.py"
models:
    image: tp33/django-docker:1.3
    external_links:
        - mysql:db
    ports:
        - "8001:8000"
    volumes:
        - ./model_api:/app
    command: bash -c "python /app/manage.py migrate && python /app/manage.py loaddata /app/fixtures/data.json && mod_wsgi-express start-server --reload-on-changes model_api/wsgi.py"  
exp:
    image: tp33/django-docker:1.3
    links:
       - models:models-api
       - kafka:kafka
       - es:es
    ports:
       - "8002:8000"
    volumes:
       - ./experience_api:/app
    command: bash -c "pip install requests && mod_wsgi-express start-server --reload-on-changes experience_api/wsgi.py"
web:
    image: tp33/django-docker:1.3
    links:
       - exp:exp-api
    ports:
       - "8000:8000"
    volumes:
       - ./frontend:/app
    command: bash -c "pip install requests && mod_wsgi-express start-server --reload-on-changes frontend/wsgi.py"
